on:
  - workflow_dispatch
  - push
    
jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - uses: "octosteve/docker-action-spike@main"
        env:
          GITHUB_TOKEN: ${{ github.token }}
